### ISSUE TITLE
Sito - vetrina

### ISSUE THREAD

**Issue by agazzarini** [gmm89/acmeinc#2]
Serve un sito monopagina sulla falsa riga di quello che aveva fatto vedere @ubdesign. Per adesso completamente statico e con contenuti falocchi. Da lì deve essere possibile accedere alla pagina di login.

**Comment by gmm89** [comment]
http://www.mrwebmaster.it/templates/androidian_6377.html

**Comment by gmm89** [comment]
scusa volevo dire questo: http://www.mrwebmaster.it/demo/templates_6397.html

**Comment by gmm89** [comment]
alternative
http://www.mrwebmaster.it/templates/brushed-template_11407.html
http://www.mrwebmaster.it/templates/proper_6401.html

**Comment by agazzarini** [comment]
Mamma mia, premesso che io non riesco a mettere due colori assieme, a me
piacciono tutti quindi non faccio testo.

@Umberto: che dici? Quale è + adatto secondo te per quello che dobbiamo
comunicare?

2015-10-12 18:31 GMT+02:00 Gianmarco <notifications@github.com>:

**Comment by ubdesign** [comment]
http://demo.html5xcss3.com/demo.php?cat=html5themes&host=365bootstrap&temp=SkullBiker

**Comment by ubdesign** [comment]
http://demo.html5xcss3.com/demo.php?cat=html5themes&host=w3layouts&temp=thefactory

**Comment by ubdesign** [comment]
http://codepen.io/Lewitje/full/BNNJjo/

**Comment by ubdesign** [comment]
http://tympanus.net/Freebies/HalcyonDaysTemplate/

**Comment by ubdesign** [comment]
https://colorlib.com/sparkling/

**Comment by ubdesign** [comment]
https://colorlib.com/dazzling/

**Comment by ubdesign** [comment]
http://technext.github.io/SIGHT/index-one-page.html

**Comment by ubdesign** [comment]
http://demo.themewagon.com/preview/timer-free-responsive-multi-page-personal-bootstrap-template

**Comment by ubdesign** [comment]
http://webflow.com/template/Velocity

**Comment by ubdesign** [comment]
http://webflow.com/template/Metric

**Comment by agazzarini** [comment]
A regà per me è veramente difficile :) Ma questo http://technext.github.io/SIGHT/index-one-page.html? Con le facciacce nostre? Mica male come idea!

**Comment by gmm89** [comment]
Lista Template:

- Gianmarco
http://www.mrwebmaster.it/demo/templates_6397.html
http://www.mrwebmaster.it/templates/brushed-template_11407.html
http://www.mrwebmaster.it/templates/proper_6401.html

- Umberto
http://demo.html5xcss3.com/demo.php?cat=html5themes&host=365bootstrap&temp=SkullBiker
http://demo.html5xcss3.com/demo.php?cat=html5themes&host=w3layouts&temp=thefactory
http://codepen.io/Lewitje/full/BNNJjo/
http://tympanus.net/Freebies/HalcyonDaysTemplate/
https://colorlib.com/sparkling/
https://colorlib.com/dazzling/
http://technext.github.io/SIGHT/index-one-page.html
http://demo.themewagon.com/preview/timer-free-responsive-multi-page-personal-bootstrap-template
http://webflow.com/template/Velocity
http://webflow.com/template/Metric

**Comment by gmm89** [comment]
Ho fatto un po di ordine, ora iniziamo a caricare il tema

**Comment by gmm89** [comment]
il tema scelto http://technext.github.io/SIGHT/index-one-page.html, non supporta wordpress, e non ha lo slide in home page... cosa vogliamo fare? cambiato tema o smanettiamo col codice? io cmq consiglio un approccio con wordpress

**Comment by agazzarini** [comment]
+1 per l'approccio wordpress. Se possibile almeno per queste cose evitiamo le cose a manazza

**Comment by gmm89** [comment]
Giovedì abbiamo discusso su quale tema utilizzare, ed abbiamo optato per il tema SIGHT http://technext.github.io/SIGHT/index-one-page.html .

Il tema non supporta wordpress, quindi per qualsiasi modifica sarà necessario mettere mano al codice (comunque sembra scritto in modo ordinato). Chiudo il topic
